services:
  minigram:
    build: .
    container_name: minigram_app
    ports:
      - "${PUBLIC_PORT:-5000}:${APP_PORT:-5000}"
    env_file:
      - .env
    volumes:
      - ./data:/app/data
    restart: unless-stopped
    cap_add:
      - IPC_LOCK
    ulimits:
      memlock:
        soft: -1
        hard: -1